name: "Changelog"
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

env:
  python-version: 3.14
  base-branch: main

jobs:
  config:
    uses: ./.github/workflows/config.yml

  checks:
    runs-on: ubuntu-latest
    needs:
      - config
    steps:
      - uses: actions/checkout@v7
        with:
          # Fetch all history
          fetch-depth: '0'

      - name: Setup uv
        uses: plone/meta/.github/actions/setup_uv@2.x
        with:
          python-version: ${{ env.python-version }}
          working-directory: '.'

      - name: "Fetch base branch"
        run: |
          git fetch --no-tags origin ${{ env.base-branch }}

      - name: "Backend: Check"
        id: backend-changelog
        if: ${{ always() && needs.config.outputs.changelog-backend == 'true' }}
        run: |
          git fetch --no-tags origin ${{ env.base-branch }}
          uvx towncrier check  --compare-with origin/${{ env.base-branch }} --config backend/pyproject.toml --dir backend/

      - name: "Frontend: Check"
        id: frontend-changelog
        if: ${{ always() && needs.config.outputs.changelog-frontend == 'true' }}
        run: |
          git fetch --no-tags origin ${{ env.base-branch }}
          uvx towncrier check  --compare-with origin/${{ env.base-branch }} --config ${{ needs.config.outputs.path-frontend }}/towncrier.toml --dir ${{ needs.config.outputs.path-frontend }}

      - name: "Repository: Check"
        id: repository-changelog
        if: ${{ always() && needs.config.outputs.changelog-repository == 'true' }}
        run: |
          git fetch --no-tags origin ${{ env.base-branch }}
          uvx towncrier check  --compare-with origin/${{ env.base-branch }} --config ${{ needs.config.outputs.path-root }}/towncrier.toml --dir ${{ needs.config.outputs.path-root }}

      - name: "Report check"
        run: |
          echo '# Workflow Report' >> $GITHUB_STEP_SUMMARY
          echo '| Job ID | Conclusion |' >> $GITHUB_STEP_SUMMARY
          echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
          echo '| backend | ${{ steps.backend-changelog.conclusion }} |' >> $GITHUB_STEP_SUMMARY
          echo '| frontend | ${{ steps.frontend-changelog.conclusion }} |' >> $GITHUB_STEP_SUMMARY
          echo '| repository | ${{ steps.repository-changelog.conclusion }} |' >> $GITHUB_STEP_SUMMARY
